#!/usr/bin/env python3
"""Generate one static page per project: work/<id>.html (+ assets/art.js).

Source of truth: the #casesData JSON block, header, footer and card-art code in index.html.
Re-run after editing the project data:  python3 build.py
"""
import json
import re
from html import escape
from pathlib import Path

ROOT = Path(__file__).parent
src = (ROOT / "index.html").read_text(encoding="utf-8")

data = json.loads(re.search(r'id="casesData">(.*?)</script>', src, re.S).group(1))
GROUPS = {g["id"]: g for g in data["groups"]}
CASES = data["cases"]
SITE = "hice — Research & information design studio"


def h(v):
    return escape("" if v is None else str(v), quote=True)


def to_index_links(fragment):
    """In-page anchors of the home page become links back to it."""
    return re.sub(r'href="#', 'href="../index.html#', fragment)


# --- shared header / menu / footer, taken from index.html ---------------------------
header = to_index_links(re.search(r'<header class="header".*?</header>', src, re.S).group(0))
menu = to_index_links(re.search(r'<div class="menu" id="menu".*?\n</div>\n', src, re.S).group(0))
footer = re.search(r'<footer class="footer".*?</footer>', src, re.S).group(0)
footer = re.sub(r'<form class="news".*?</form>', "", footer, flags=re.S)  # newsletter JS lives on the home page
footer = to_index_links(footer)
footer = re.sub(r'(<a href="../index.html#work")( data-filter="(\w+)")', lambda m: '<a href="../index.html#work"', footer)

# --- art.js: card illustrations (SVG) extracted from the home page script ---------------
art_start = src.index("  function el(tag, attrs, parent)")
art_end = src.index("  /* ---------- Cases:")
art_js = (
    "/* Generated by build.py from index.html — card illustrations. */\n"
    "(function () {\n  \"use strict\";\n"
    "  var NS = \"http://www.w3.org/2000/svg\";\n"
    + re.search(r"  function rng\(seed\).*?\n", src).group(0)
    + src[art_start:art_end]
    + "  window.HICE_ART = ART;\n})();\n"
)
(ROOT / "assets").mkdir(exist_ok=True)
(ROOT / "assets" / "art.js").write_text(art_js, encoding="utf-8")

ARROW_L = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 12H4M10 6l-6 6 6 6"/></svg>'
ARROW_R = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12h16M14 6l6 6-6 6"/></svg>'
EXT = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" aria-hidden="true"><path d="M7 17L17 7M8 7h9v9"/></svg>'


def art_svg(kind, label):
    return f'<svg data-art="{h(kind)}" viewBox="0 0 640 360" preserveAspectRatio="xMidYMid slice" role="img" aria-label="{h(label)}"></svg>'


def full(duo, im):
    return ' class="full"' if duo and im[1] < 0.6 else ""


def render_body(c):
    g = GROUPS[c["g"]]
    facts = f'<dl class="dlg-facts"><dt>Client</dt><dd>{h(c["client"])}</dd>'
    if c.get("year"):
        facts += f'<dt>Year</dt><dd>{h(c["year"])}</dd>'
    facts += f'<dt>Direction</dt><dd>{h(g["title"])}</dd><dt>Format</dt><dd>{h(c["badge"])}</dd>'
    if c.get("tags"):
        facts += "<dt>Tags</dt><dd>" + " · ".join(h(t) for t in c["tags"]) + "</dd>"
    facts += "</dl>"
    out = (f'<div class="dlg-head"><div><p class="label"><b>{h(c["badge"])}</b></p>'
           f'<h1 id="caseTitle">{h(c["title"])}</h1><p class="lead">{h(c["sum"])}</p></div>{facts}</div>')
    if c.get("stats"):
        out += '<ul class="stats">' + "".join(f"<li><b>{h(s[0])}</b><span>{h(s[1])}</span></li>" for s in c["stats"]) + "</ul>"

    txt = ""
    for sec in c.get("sections", []):
        body = "".join(f"<p>{h(p)}</p>" for p in (sec[1] if len(sec) > 1 else []) or [])
        if len(sec) > 2 and sec[2]:
            tag = "ol" if len(sec) > 3 and sec[3] == "ol" else "ul"
            body += f"<{tag}>" + "".join(f"<li>{h(li)}</li>" for li in sec[2]) + f"</{tag}>"
        if body:
            txt += f"<div><h3>{h(sec[0])}</h3>{body}</div>"
    if c.get("quote"):
        txt += f'<blockquote class="quote"><p>“{h(c["quote"][0])}”</p><cite>— {h(c["quote"][1])}</cite></blockquote>'
    res = [(l[0], l[1]) for l in c.get("web", [])]
    res += [(l[0] + " (interactive)", l[1]) for l in c.get("links", [])]
    res += [(l[0], l[1]) for l in c.get("files", [])]
    if res:
        title = "Live sites &amp; materials" if c.get("web") else "Materials"
        txt += f'<div><h3>{title}</h3><ul class="res-links">' + "".join(
            f'<li><a href="{h(u)}" target="_blank" rel="noopener">{h(t)} {EXT}</a></li>' for t, u in res) + "</ul></div>"

    imgs = c.get("img", [])
    duo = len(imgs) > 3 and all(i[1] < 1.3 for i in imgs)
    if imgs:
        gal = "".join(
            f'<figure{full(duo, im)}><img src="../{h(im[0])}" '
            f'alt="{h(c["title"])} — image {i + 1} of {len(imgs)}" loading="lazy" decoding="async" '
            f'style="aspect-ratio:{im[1]}"></figure>' for i, im in enumerate(imgs))
    else:
        gal = f'<figure class="art">{art_svg(c.get("art", "bars"), c["title"] + " — illustration")}</figure>'
    out += f'<div class="dlg-body"><div class="dlg-text">{txt}</div><div class="gallery{" duo" if duo else ""}">{gal}</div></div>'
    return out


# fall back to the illustration when a gallery image is missing
PAGE_JS = """<script src="../assets/art.js"></script>
<script>
(function () {
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };
  document.documentElement.classList.add("js");
  var NS = "http://www.w3.org/2000/svg";
  function draw(root) { $$("svg[data-art]", root).forEach(function (s) { if (!s.childNodes.length) window.HICE_ART[s.getAttribute("data-art")](s); }); }
  draw(document);
  var art = document.body.getAttribute("data-art") || "bars";
  $$(".gallery img").forEach(function (img, i) {
    img.addEventListener("error", function () {
      if (i !== 0) { img.parentNode.remove(); return; }
      var f = img.parentNode; f.className = "art";
      f.innerHTML = '<svg data-art="' + art + '" viewBox="0 0 640 360" preserveAspectRatio="xMidYMid slice" role="img" aria-label="' + img.alt.replace(/"/g, "") + '"></svg>';
      draw(f);
    });
  });
  var menu = document.getElementById("menu"), btn = document.getElementById("menuBtn");
  function setMenu(o) { menu.hidden = !o; btn.setAttribute("aria-expanded", String(o)); document.body.classList.toggle("menu-open", o); }
  btn.addEventListener("click", function () { setMenu(true); });
  document.getElementById("menuClose").addEventListener("click", function () { setMenu(false); });
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") setMenu(false); });
  var header = document.getElementById("header"), lastY = window.scrollY;
  window.addEventListener("scroll", function () { var y = window.scrollY; header.classList.toggle("is-hidden", y > lastY && y > 160); lastY = y; }, { passive: true });
})();
</script>"""


def page(c, i):
    g = GROUPS[c["g"]]
    same = [x for x in CASES if x["g"] == c["g"]]
    prev, nxt = CASES[(i - 1) % len(CASES)], CASES[(i + 1) % len(CASES)]
    title = f'{c["title"]} — {SITE}'
    nav = (f'<nav class="case-pager" aria-label="Projects">'
           f'<a href="{h(prev["id"])}.html" rel="prev">{ARROW_L}<span><small>Previous</small>{h(prev["title"])}</span></a>'
           f'<a href="{h(nxt["id"])}.html" rel="next"><span><small>Next</small>{h(nxt["title"])}</span>{ARROW_R}</a></nav>')
    crumb = (f'<p class="label case-crumb"><a href="../index.html#work">Work</a> / '
             f'<a href="../index.html#dir-{h(g["id"])}">{h(g["title"])}</a> / <b>{h(c["title"])}</b></p>')
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="{h(c["sum"])}">
<title>{h(title)}</title>
<link rel="stylesheet" href="../assets/site.css">
<style>
.case-page {{ padding: clamp(112px, 14vw, 160px) 0 var(--space-64, 64px); }}
.case-crumb {{ margin: 0 0 var(--space-24, 24px); }}
.case-crumb a {{ text-decoration: underline; text-underline-offset: 4px; text-decoration-color: var(--line-strong); }}
.case-crumb a:hover {{ color: var(--accent-electric); }}
.case-page .dlg-head h1 {{ margin: var(--space-16, 16px) 0 0; font: 400 clamp(36px, 4.6vw, 64px)/1.06 var(--font-display); letter-spacing: -.02em; text-wrap: balance; }}
.case-pager {{ display: grid; grid-template-columns: 1fr 1fr; gap: var(--gutter, 24px); margin-top: var(--space-64, 64px); padding-top: var(--space-32, 32px); border-top: 1px solid var(--line); }}
.case-pager a {{ display: flex; align-items: center; gap: 14px; padding: 16px 0; }}
.case-pager a:last-child {{ justify-content: flex-end; text-align: right; }}
.case-pager svg {{ width: 22px; height: 22px; flex: none; }}
.case-pager small {{ display: block; font: 600 11px/1.6 var(--font-sans); letter-spacing: .08em; text-transform: uppercase; color: var(--ink-muted); }}
.case-pager a:hover {{ color: var(--accent-electric); }}
@media (max-width: 600px) {{ .case-pager {{ grid-template-columns: 1fr; }} .case-pager a:last-child {{ justify-content: flex-start; text-align: left; flex-direction: row-reverse; }} }}
</style>
</head>
<body data-art="{h(c.get("art", "bars"))}">
<a class="skip" href="#main">Skip to content</a>

{header}

{menu}
<main id="main" class="case-page">
  <div class="wrap">
    {crumb}
    {render_body(c)}
    {nav}
  </div>
</main>

{footer}
{PAGE_JS}
</body>
</html>
"""


out_dir = ROOT / "work"
out_dir.mkdir(exist_ok=True)
for i, c in enumerate(CASES):
    (out_dir / f'{c["id"]}.html').write_text(page(c, i), encoding="utf-8")
print(f"built {len(CASES)} project pages + assets/art.js")
